basePath: /
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API VMCod3r GO
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: VMCod3r
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: 1.0.0
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
